/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author watel
 */
public class CadastrarImoveis extends javax.swing.JFrame
{

    /**
     * Creates new form CadastrarImoveis
     */
    public CadastrarImoveis()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPreco = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnCadastrarImoveis = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        boxT = new javax.swing.JComboBox<>();
        boxD = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        txtNQ = new javax.swing.JTextField();
        txtNomeI = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        btnVoltar3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("CASA EFICIENTE");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(222, 154, 74));
        jLabel2.setText("IMOVEL");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 220, 60));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(222, 154, 74));
        jLabel3.setText("Cadastro de");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 120, -1));

        jLabel4.setText("Preencha os campos abaixo com os dados do seu");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, -1, -1));

        txtPreco.setBackground(new java.awt.Color(102, 102, 102));
        txtPreco.setForeground(new java.awt.Color(204, 204, 204));
        txtPreco.setText("00,00\tKz");
        txtPreco.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                txtPrecoMouseEntered(evt);
            }
        });
        txtPreco.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtPrecoActionPerformed(evt);
            }
        });
        jPanel1.add(txtPreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, 120, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(222, 154, 74));
        jLabel5.setText("Disponibilidade");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(222, 154, 74));
        jLabel7.setText("Endereco");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, -1, -1));

        btnCadastrarImoveis.setBackground(new java.awt.Color(222, 154, 74));
        btnCadastrarImoveis.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCadastrarImoveis.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrarImoveis.setText("Cadastrar Imoveis");
        btnCadastrarImoveis.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCadastrarImoveisActionPerformed(evt);
            }
        });
        jPanel1.add(btnCadastrarImoveis, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 470, 160, 40));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(222, 154, 74));
        jLabel10.setText("Numero de Quartos");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, 180, -1));
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(222, 154, 74));
        jLabel13.setText("Preco");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 390, 100, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginTela/IMOVEL1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 560));

        boxT.setBackground(new java.awt.Color(102, 102, 102));
        boxT.setForeground(new java.awt.Color(204, 204, 204));
        boxT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Residencial", "Comercial" }));
        jPanel1.add(boxT, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 120, 30));

        boxD.setBackground(new java.awt.Color(102, 102, 102));
        boxD.setForeground(new java.awt.Color(204, 204, 204));
        boxD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Desocupado", "Ocupado" }));
        jPanel1.add(boxD, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 270, 120, 30));

        jLabel9.setText("imovel.");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(222, 154, 74));
        jLabel14.setText("Tipo de imovel");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, -1, -1));

        txtEndereco.setBackground(new java.awt.Color(102, 102, 102));
        txtEndereco.setForeground(new java.awt.Color(204, 204, 204));
        txtEndereco.setText("Ex: Av. 21 de Janeiro");
        txtEndereco.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                txtEnderecoMouseEntered(evt);
            }
        });
        txtEndereco.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtEnderecoActionPerformed(evt);
            }
        });
        jPanel1.add(txtEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, 330, 30));

        txtNQ.setBackground(new java.awt.Color(102, 102, 102));
        txtNQ.setForeground(new java.awt.Color(204, 204, 204));
        txtNQ.setText("00");
        txtNQ.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                txtNQMouseEntered(evt);
            }
        });
        txtNQ.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtNQActionPerformed(evt);
            }
        });
        jPanel1.add(txtNQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, 120, 40));

        txtNomeI.setBackground(new java.awt.Color(102, 102, 102));
        txtNomeI.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNomeI.setForeground(new java.awt.Color(204, 204, 204));
        txtNomeI.setText("Descricao");
        txtNomeI.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                txtNomeIMouseEntered(evt);
            }
        });
        jPanel1.add(txtNomeI, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 320, 30));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(222, 154, 74));
        jLabel15.setText("Nome do Imovel");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, -1, -1));

        btnVoltar3.setBackground(new java.awt.Color(102, 102, 102));
        btnVoltar3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVoltar3.setForeground(new java.awt.Color(255, 255, 255));
        btnVoltar3.setText("Voltar ao Menu");
        btnVoltar3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnVoltar3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnVoltar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 490, 140, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 744, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 544, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPrecoMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_txtPrecoMouseEntered
    {//GEN-HEADEREND:event_txtPrecoMouseEntered
        // TODO add your handling code here:
        txtPreco.setText("");
    }//GEN-LAST:event_txtPrecoMouseEntered

    private void txtPrecoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtPrecoActionPerformed
    {//GEN-HEADEREND:event_txtPrecoActionPerformed
        txtPreco.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecoActionPerformed

    private void btnCadastrarImoveisActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCadastrarImoveisActionPerformed
    {//GEN-HEADEREND:event_btnCadastrarImoveisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCadastrarImoveisActionPerformed

    private void txtEnderecoMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_txtEnderecoMouseEntered
    {//GEN-HEADEREND:event_txtEnderecoMouseEntered
        // TODO add your handling code here:
        this.txtEndereco.setText("");
    }//GEN-LAST:event_txtEnderecoMouseEntered

    private void txtEnderecoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtEnderecoActionPerformed
    {//GEN-HEADEREND:event_txtEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnderecoActionPerformed

    private void txtNQMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_txtNQMouseEntered
    {//GEN-HEADEREND:event_txtNQMouseEntered
        // TODO add your handling code here:
        this.txtNQ.setText("");
    }//GEN-LAST:event_txtNQMouseEntered

    private void txtNQActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtNQActionPerformed
    {//GEN-HEADEREND:event_txtNQActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNQActionPerformed

    private void txtNomeIMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_txtNomeIMouseEntered
    {//GEN-HEADEREND:event_txtNomeIMouseEntered
        // TODO add your handling code here:
        txtNomeI.setText("");
    }//GEN-LAST:event_txtNomeIMouseEntered

    private void btnVoltar3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnVoltar3ActionPerformed
    {//GEN-HEADEREND:event_btnVoltar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVoltar3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(CadastrarImoveis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(CadastrarImoveis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(CadastrarImoveis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(CadastrarImoveis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new CadastrarImoveis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxD;
    private javax.swing.JComboBox<String> boxT;
    private javax.swing.JButton btnCadastrarImoveis;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JButton btnVoltar1;
    private javax.swing.JButton btnVoltar2;
    private javax.swing.JButton btnVoltar3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNQ;
    private javax.swing.JTextField txtNomeI;
    private javax.swing.JTextField txtPreco;
    // End of variables declaration//GEN-END:variables
}
