/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author watel
 */
public class GerarContrato extends javax.swing.JFrame
{

    /**
     * Creates new form GerarContrato
     */
    public GerarContrato()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        txtEmail = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSobrenome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNBI = new javax.swing.JTextField();
        txtPreco = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNomeC = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNF = new javax.swing.JTextField();
        btnVoltar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        boxT = new javax.swing.JComboBox<>();
        boxD = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        txtNQ = new javax.swing.JTextField();
        txtNomeI = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnAlterarImoveis1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtEmail.setForeground(new java.awt.Color(51, 51, 51));
        txtEmail.setText("exemplo@CasaEficiente.com");
        txtEmail.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                txtEmailMouseEntered(evt);
            }
        });
        txtEmail.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtEmailActionPerformed(evt);
            }
        });
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 250, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("CASA EFICIENTE");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 490, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(222, 154, 74));
        jLabel16.setText("Nome Completo");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(222, 154, 74));
        jLabel2.setText("CONTRATO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 220, 60));

        txtSobrenome.setForeground(new java.awt.Color(51, 51, 51));
        txtSobrenome.setText("Joao Apolinario");
        txtSobrenome.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                txtSobrenomeMouseEntered(evt);
            }
        });
        jPanel1.add(txtSobrenome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 250, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(222, 154, 74));
        jLabel3.setText("GERAR");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 170, -1));

        txtNBI.setForeground(new java.awt.Color(102, 102, 102));
        txtNBI.setText("0006342317LA098");
        txtNBI.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                txtNBIMouseEntered(evt);
            }
        });
        jPanel1.add(txtNBI, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 240, 30));

        txtPreco.setBackground(new java.awt.Color(102, 102, 102));
        txtPreco.setForeground(new java.awt.Color(204, 204, 204));
        txtPreco.setText("00,00\tKz");
        txtPreco.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                txtPrecoMouseEntered(evt);
            }
        });
        txtPreco.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtPrecoActionPerformed(evt);
            }
        });
        jPanel1.add(txtPreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 390, 120, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(222, 154, 74));
        jLabel5.setText("Disponibilidade");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, -1, -1));

        txtNomeC.setForeground(new java.awt.Color(102, 102, 102));
        txtNomeC.setText("Joao Apolinario");
        txtNomeC.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                txtNomeCMouseEntered(evt);
            }
        });
        txtNomeC.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtNomeCActionPerformed(evt);
            }
        });
        jPanel1.add(txtNomeC, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 240, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(222, 154, 74));
        jLabel7.setText("Endereco");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, -1, -1));

        txtNF.setForeground(new java.awt.Color(102, 102, 102));
        txtNF.setText("+244 999 999 999");
        txtNF.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                txtNFMouseEntered(evt);
            }
        });
        jPanel1.add(txtNF, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 240, 30));

        btnVoltar.setBackground(new java.awt.Color(102, 102, 102));
        btnVoltar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(255, 255, 255));
        btnVoltar.setText("Voltar ao Menu");
        btnVoltar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnVoltarActionPerformed(evt);
            }
        });
        jPanel1.add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 480, 140, 20));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(222, 154, 74));
        jLabel10.setText("Numero de Quartos");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, 180, -1));
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(222, 154, 74));
        jLabel17.setText("E-mail");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(222, 154, 74));
        jLabel13.setText("Preco");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 370, 100, -1));

        boxT.setBackground(new java.awt.Color(102, 102, 102));
        boxT.setForeground(new java.awt.Color(204, 204, 204));
        boxT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Residencial", "Comercial" }));
        jPanel1.add(boxT, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 120, 30));

        boxD.setBackground(new java.awt.Color(102, 102, 102));
        boxD.setForeground(new java.awt.Color(204, 204, 204));
        boxD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Desocupado", "Ocupado" }));
        jPanel1.add(boxD, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, 120, 30));

        jLabel9.setText("Hora de fechar negocio.");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(222, 154, 74));
        jLabel14.setText("Tipo de imovel");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, -1, -1));

        txtEndereco.setBackground(new java.awt.Color(102, 102, 102));
        txtEndereco.setForeground(new java.awt.Color(204, 204, 204));
        txtEndereco.setText("Ex: Av. 21 de Janeiro");
        txtEndereco.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                txtEnderecoMouseEntered(evt);
            }
        });
        txtEndereco.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtEnderecoActionPerformed(evt);
            }
        });
        jPanel1.add(txtEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 330, 30));

        txtNQ.setBackground(new java.awt.Color(102, 102, 102));
        txtNQ.setForeground(new java.awt.Color(204, 204, 204));
        txtNQ.setText("00");
        txtNQ.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                txtNQMouseEntered(evt);
            }
        });
        txtNQ.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtNQActionPerformed(evt);
            }
        });
        jPanel1.add(txtNQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, 120, 40));

        txtNomeI.setBackground(new java.awt.Color(102, 102, 102));
        txtNomeI.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNomeI.setForeground(new java.awt.Color(204, 204, 204));
        txtNomeI.setText("Descricao");
        txtNomeI.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                txtNomeIMouseEntered(evt);
            }
        });
        jPanel1.add(txtNomeI, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 320, 30));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(222, 154, 74));
        jLabel15.setText("Nome do Imovel");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Dados do Cliente");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 170, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(222, 154, 74));
        jLabel18.setText("Numero do BI");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, -1, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(222, 154, 74));
        jLabel23.setText("Terminal Telefonico");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(222, 154, 74));
        jLabel25.setText("Nome do Cliente");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Dados do Corretor");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 170, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gerar1.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 550));

        btnAlterarImoveis1.setBackground(new java.awt.Color(222, 154, 74));
        btnAlterarImoveis1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAlterarImoveis1.setForeground(new java.awt.Color(255, 255, 255));
        btnAlterarImoveis1.setText("Alterar Imoveis");
        btnAlterarImoveis1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAlterarImoveis1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnAlterarImoveis1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 460, 160, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 744, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 544, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPrecoMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_txtPrecoMouseEntered
    {//GEN-HEADEREND:event_txtPrecoMouseEntered
        // TODO add your handling code here:
        txtPreco.setText("");
    }//GEN-LAST:event_txtPrecoMouseEntered

    private void txtPrecoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtPrecoActionPerformed
    {//GEN-HEADEREND:event_txtPrecoActionPerformed
        txtPreco.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecoActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnVoltarActionPerformed
    {//GEN-HEADEREND:event_btnVoltarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void txtEnderecoMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_txtEnderecoMouseEntered
    {//GEN-HEADEREND:event_txtEnderecoMouseEntered
        // TODO add your handling code here:
        this.txtEndereco.setText("");
    }//GEN-LAST:event_txtEnderecoMouseEntered

    private void txtEnderecoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtEnderecoActionPerformed
    {//GEN-HEADEREND:event_txtEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnderecoActionPerformed

    private void txtNQMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_txtNQMouseEntered
    {//GEN-HEADEREND:event_txtNQMouseEntered
        // TODO add your handling code here:
        this.txtNQ.setText("");
    }//GEN-LAST:event_txtNQMouseEntered

    private void txtNQActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtNQActionPerformed
    {//GEN-HEADEREND:event_txtNQActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNQActionPerformed

    private void txtNomeIMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_txtNomeIMouseEntered
    {//GEN-HEADEREND:event_txtNomeIMouseEntered
        // TODO add your handling code here:
        txtNomeI.setText("");
    }//GEN-LAST:event_txtNomeIMouseEntered

    private void txtSobrenomeMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_txtSobrenomeMouseEntered
    {//GEN-HEADEREND:event_txtSobrenomeMouseEntered
        txtSobrenome.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_txtSobrenomeMouseEntered

    private void txtEmailMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_txtEmailMouseEntered
    {//GEN-HEADEREND:event_txtEmailMouseEntered
        // TODO add your handling code here:
        txtEmail.setText("");
    }//GEN-LAST:event_txtEmailMouseEntered

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtEmailActionPerformed
    {//GEN-HEADEREND:event_txtEmailActionPerformed
        txtEmail.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtNomeCActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtNomeCActionPerformed
    {//GEN-HEADEREND:event_txtNomeCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeCActionPerformed

    private void txtNomeCMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_txtNomeCMouseEntered
    {//GEN-HEADEREND:event_txtNomeCMouseEntered
        // TODO add your handling code here:
        this.txtNomeC.setText("");
    }//GEN-LAST:event_txtNomeCMouseEntered

    private void txtNBIMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_txtNBIMouseEntered
    {//GEN-HEADEREND:event_txtNBIMouseEntered
        // TODO add your handling code here:
        this.txtNBI.setText("");
    }//GEN-LAST:event_txtNBIMouseEntered

    private void txtNFMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_txtNFMouseEntered
    {//GEN-HEADEREND:event_txtNFMouseEntered
        // TODO add your handling code here:
        this.txtNF.setText("");
    }//GEN-LAST:event_txtNFMouseEntered

    private void btnAlterarImoveis1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAlterarImoveis1ActionPerformed
    {//GEN-HEADEREND:event_btnAlterarImoveis1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlterarImoveis1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(GerarContrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(GerarContrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(GerarContrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(GerarContrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new GerarContrato().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxD;
    private javax.swing.JComboBox<String> boxT;
    private javax.swing.JButton btnAlterarImoveis1;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNBI;
    private javax.swing.JTextField txtNF;
    private javax.swing.JTextField txtNQ;
    private javax.swing.JTextField txtNomeC;
    private javax.swing.JTextField txtNomeI;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtSobrenome;
    // End of variables declaration//GEN-END:variables
}
