/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package loginTela;

/**
 *
 * @author watel
 */
public class CadastroCorretor extends javax.swing.JFrame
{

    /**
     * Creates new form CadastroCorretor
     */
    public CadastroCorretor()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNomeCompleto = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnCadastrarCorretor = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtPassSenha1 = new javax.swing.JPasswordField();
        txtPassSenha2 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("CASA EFICIENTE");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 450, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(222, 154, 74));
        jLabel2.setText("CORRETOR");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 220, 60));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(222, 154, 74));
        jLabel3.setText("Cadastro de");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 120, -1));

        jLabel4.setText("Entre com os dados do corretor.");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, -1, -1));

        txtNomeCompleto.setBackground(new java.awt.Color(102, 102, 102));
        txtNomeCompleto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtNomeCompleto.setForeground(new java.awt.Color(255, 255, 255));
        txtNomeCompleto.setText("Joao Apolinario");
        txtNomeCompleto.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                txtNomeCompletoMouseEntered(evt);
            }
        });
        jPanel1.add(txtNomeCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 290, -1));

        txtEmail.setBackground(new java.awt.Color(102, 102, 102));
        txtEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtEmail.setText("exemplo@CasaEficiente.com");
        txtEmail.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                txtEmailMouseEntered(evt);
            }
        });
        txtEmail.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtEmailActionPerformed(evt);
            }
        });
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, 290, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(222, 154, 74));
        jLabel5.setText("Nome Completo");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(222, 154, 74));
        jLabel6.setText("Voltar ao menu principal");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 470, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(222, 154, 74));
        jLabel7.setText("E-mail");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, -1, -1));

        btnCadastrarCorretor.setBackground(new java.awt.Color(222, 154, 74));
        btnCadastrarCorretor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCadastrarCorretor.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrarCorretor.setText("Cadastrar Corretor");
        btnCadastrarCorretor.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCadastrarCorretorActionPerformed(evt);
            }
        });
        jPanel1.add(btnCadastrarCorretor, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 410, 160, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(222, 154, 74));
        jLabel10.setText("Confirmar - Senha de Acesso");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, 180, -1));

        jLabel12.setText("Mais um corretor!");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(222, 154, 74));
        jLabel13.setText("Senha de Acesso");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, 100, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginTela/corretor2.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        txtPassSenha1.setBackground(new java.awt.Color(102, 102, 102));
        txtPassSenha1.setForeground(new java.awt.Color(255, 255, 255));
        txtPassSenha1.setText("jPasswordField1");
        txtPassSenha1.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                txtPassSenha1MouseEntered(evt);
            }
        });
        jPanel1.add(txtPassSenha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, 290, -1));

        txtPassSenha2.setBackground(new java.awt.Color(102, 102, 102));
        txtPassSenha2.setForeground(new java.awt.Color(255, 255, 255));
        txtPassSenha2.setText("jPasswordField2");
        txtPassSenha2.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                txtPassSenha2MouseExited(evt);
            }
        });
        jPanel1.add(txtPassSenha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 370, 290, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeCompletoMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_txtNomeCompletoMouseEntered
    {//GEN-HEADEREND:event_txtNomeCompletoMouseEntered
        txtNomeCompleto.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeCompletoMouseEntered

    private void txtEmailMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_txtEmailMouseEntered
    {//GEN-HEADEREND:event_txtEmailMouseEntered
        // TODO add your handling code here:
        txtEmail.setText("");
    }//GEN-LAST:event_txtEmailMouseEntered

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtEmailActionPerformed
    {//GEN-HEADEREND:event_txtEmailActionPerformed
        txtEmail.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void btnCadastrarCorretorActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCadastrarCorretorActionPerformed
    {//GEN-HEADEREND:event_btnCadastrarCorretorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCadastrarCorretorActionPerformed

    private void txtPassSenha1MouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_txtPassSenha1MouseEntered
    {//GEN-HEADEREND:event_txtPassSenha1MouseEntered
        // TODO add your handling code here:
        txtPassSenha1.setText("");
    }//GEN-LAST:event_txtPassSenha1MouseEntered

    private void txtPassSenha2MouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_txtPassSenha2MouseExited
    {//GEN-HEADEREND:event_txtPassSenha2MouseExited
        // TODO add your handling code here:
        txtPassSenha2.setText("");
    }//GEN-LAST:event_txtPassSenha2MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(CadastroCorretor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(CadastroCorretor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(CadastroCorretor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(CadastroCorretor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new CadastroCorretor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarCorretor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNomeCompleto;
    private javax.swing.JPasswordField txtPassSenha1;
    private javax.swing.JPasswordField txtPassSenha2;
    // End of variables declaration//GEN-END:variables
}
